/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#7b68ee",
        "on-primary": "#ffffff",
        "primary-container": "#e8e5ff",
        "on-primary-container": "#1d0061",
        secondary: "#5d5c7d",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2e0ff",
        "on-secondary-container": "#191937",
        tertiary: "#7c5263",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ffd8e5",
        "on-tertiary-container": "#31101f",
        background: "#f8f9ff",
        "on-background": "#1a1b21",
        surface: "#f8f9ff",
        "on-surface": "#1a1b21",
        "surface-variant": "#e4e1f1",
        "on-surface-variant": "#474653",
        outline: "#777685",
        "outline-variant": "#c8c5d6",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3fb",
        "surface-container": "#eeecf6",
        "surface-container-high": "#e8e7f0",
        "surface-container-highest": "#e2e1ea",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        headline: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "8px",
        none: "0",
        sm: "4px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        full: "9999px",
      },
      keyframes: {
        "slide-in-right": {
          from: { transform: "translateX(24px)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
      },
      animation: {
        "slide-in-right": "slide-in-right 0.28s cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
