import {
  LayoutDashboard,
  Code2,
  Megaphone,
  FlaskConical,
  FileText,
  Globe,
  ShieldCheck,
  Layers,
  MonitorPlay,
  Database,
  PenTool,
  Inbox,
  BookMarked,
  Telescope,
  Folder,
  FolderOpen,
  FolderKanban,
  FolderGit2,
  FolderHeart,
  FolderLock,
  FolderSearch,
  FolderSync,
  FolderTree,
  FolderCheck,
  FolderClock,
  FolderArchive,
  FolderInput,
  FolderOutput,
  FolderMinus,
  FolderPlus,
  FolderX,
  FolderSymlink,
  FolderDot,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  ListTree,
  ListFilter,
  ListVideo,
  ListMusic,
  ListCollapse,
  ListEnd,
  ListMinus,
  ListPlus,
  ListRestart,
  ListStart,
  ListX,
} from "lucide-react";

const ICON_MAP: Record<string, React.ElementType> = {
  FolderKanban,
  LayoutDashboard,
  Code2,
  Megaphone,
  FlaskConical,
  FileText,
  Globe,
  ShieldCheck,
  Layers,
  MonitorPlay,
  Database,
  PenTool,
  Inbox,
  BookMarked,
  Telescope,
  Folder,
  FolderOpen,
  FolderGit2,
  FolderHeart,
  FolderLock,
  FolderSearch,
  FolderSync,
  FolderTree,
  FolderCheck,
  FolderClock,
  FolderArchive,
  FolderInput,
  FolderOutput,
  FolderMinus,
  FolderPlus,
  FolderX,
  FolderSymlink,
  FolderDot,
  List,
  ListChecks,
  ListOrdered,
  ListTodo,
  ListTree,
  ListFilter,
  ListVideo,
  ListMusic,
  ListCollapse,
  ListEnd,
  ListMinus,
  ListPlus,
  ListRestart,
  ListStart,
  ListX,
};

export const Icon = ({
  icon,
  className,
  style,
  size,
}: {
  icon?: string;
  className?: string;
  style?: React.CSSProperties;
  size?: number;
}) => {
  const Icon = (icon && ICON_MAP[icon]) || Folder;
  return (
    <Icon className={className} style={style} strokeWidth={1.75} size={size} />
  );
};
